---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-kibana-custom-nodejs-builds
  description: Buildkite Pipeline for kibana-custom-nodejs-builds
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/kibana-custom-nodejs-builds

spec:
  type: buildkite-pipeline
  owner: group:kibana-operations
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: kibana-custom-nodejs-builds
    spec:
      repository: elastic/kibana-custom-nodejs-builds
      pipeline_file: ".buildkite/pipeline.yml"
      teams:
        kibana-operations:
        access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
