---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kibana-custom-node-dot-js-builds
  description: Buildkite Pipeline for kibana-custom-nodejs-builds
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/kibana-custom-node-dot-js-builds
spec:
  owner: group:kibana-operations
  type: tool
