---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kibana-custom-node-dot-js-builds
  description: Buildkite Pipeline for kibana-custom-nodejs-builds
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/kibana-custom-node-dot-js-builds
spec:
  owner: group:kibana-operations
  type: tool
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: bk-kibana-custom-node-js-builds
  description: Custom nodejs builds for old platforms
  links:
    - url: 'https://buildkite.com/elastic/kibana-custom-node-dot-js-builds'
      title: Pipeline link
spec:
  type: buildkite-pipeline
  owner: 'group:kibana-operations'
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: kibana / custom node.js builds
      description: Custom nodejs builds for old platforms
    spec:
      env:
        SLACK_NOTIFICATIONS_CHANNEL: '#kibana-operations-alerts'
        ELASTIC_SLACK_NOTIFICATIONS_ENABLED: 'true'
      allow_rebuilds: true
      branch_configuration: main
      default_branch: main
      repository: elastic/kibana-custom-nodejs-builds
      pipeline_file: .buildkite/pipeline.yml
      skip_intermediate_builds: false
      provider_settings:
        build_branches: true
        build_pull_requests: false
        publish_commit_status: false
        trigger_mode: none
        build_tags: false
        prefix_pull_request_fork_branch_names: false
        skip_pull_request_builds_for_existing_commits: false
      teams:
        everyone:
          access_level: READ_ONLY
        kibana-operations:
          access_level: MANAGE_BUILD_AND_READ
        kibana-tech-leads:
          access_level: MANAGE_BUILD_AND_READ
