steps:
  - command: echo "OK"
    label: Blank command, placeholder

  # - command: scripts/create_build_images.sh
  #   label: Creating build images
  #   env:
  #     ARCH: amd64

  # - command: scripts/create_build_images.sh
  #   label: Creating build images
  #   env:
  #     ARCH: arm64

  # - wait

  # - command:
  #     - scripts/build_nodejs.sh
  #   label: Building node.js
  #   env:
  #     ARCH: amd64
  #   timeout_in_minutes: 300

  # - command: scripts/build_nodejs.sh
  #   env:
  #     ARCH: arm64
  #   label: Build node.js
  #   timeout_in_minutes: 600
