steps:
  - command:
      - which gsutil
      - scripts/create_build_images.sh
      - scripts/build_nodejs.sh
      - scripts/upload_artifacts.sh
    label: Creating build images
    env:
      ARCH: amd64
      TARGET_VERSION: 18.15.0
    agents:
      queue: kibana-default

  # - command:
  #     - scripts/create_build_images.sh
  #     - scripts/build_nodejs.sh
  #   label: Creating build images
  #   env:
  #     ARCH: arm64
  #   agents:
  #     queue: macos-arm
