env:
  TARGET_VERSION: 20.15.1

steps:
  - label: Annotate build with node version
    command:
      - scripts/annotate_build.sh
  
  - label: Build custom node.js artifacts with glibc 2.17 for x64
    command:
      - scripts/create_build_images.sh
      - scripts/build_nodejs.sh
      - scripts/upload_nodejs_artifacts.sh
    env:
      TARGET_ARCH: amd64
      TARGET_VARIANT: 'glibc-217'
    agents:
      image: family/kibana-ubuntu-2004
      provider: gcp
      machineType: c2-standard-16
    timeout_in_minutes: 60 # ideally runs in ~30m

  - label: Build custom node.js artifacts with glibc 2.17 for arm64
    command:
      - scripts/create_build_images.sh
      - scripts/build_nodejs.sh
      - scripts/upload_nodejs_artifacts.sh
    env:
      TARGET_ARCH: arm64
      TARGET_VARIANT: 'glibc-217'
    agents:
      image: family/kibana-ubuntu-2004
      imageProject: elastic-images-qa
      provider: gcp
      machineType: c2-standard-60
    timeout_in_minutes: 180 # ideally runs in ~2hr

  - label: Build custom node.js artifacts with pointer compression for x64
    if: build.env('SKIP_POINTER_COMPRESSION') == null
    command:
      - scripts/create_build_images.sh
      - scripts/build_nodejs.sh
      - scripts/upload_nodejs_artifacts.sh
    env:
      TARGET_ARCH: amd64
      TARGET_VARIANT: 'pointer-compression'
    agents:
      image: family/kibana-ubuntu-2004
      provider: gcp
      machineType: c2-standard-16
    timeout_in_minutes: 60 # ideally runs in ~30m

  - label: Build custom node.js artifacts with pointer compression for arm64
    if: build.env('SKIP_POINTER_COMPRESSION') == null
    command:
      - scripts/create_build_images.sh
      - scripts/build_nodejs.sh
      - scripts/upload_nodejs_artifacts.sh
    env:
      TARGET_ARCH: arm64
      TARGET_VARIANT: 'pointer-compression'
    agents:
      image: family/kibana-ubuntu-2004
      provider: gcp
      machineType: c2-standard-60
    timeout_in_minutes: 180 # ideally runs in ~2hr

  - wait

  - label: Fix SHASUMS256.txt with newly built files' hashes with glibc 2.17
    command:
      - scripts/replace_sha_hashes.sh
    env:
      TARGET_VARIANT: 'glibc-217'
    agents:
      image: family/kibana-ubuntu-2004
      provider: gcp
      machineType: n2-standard-2

  - label: Fix SHASUMS256.txt with newly built files' hashes with pointer compression
    if: build.env('SKIP_POINTER_COMPRESSION') == null
    command:
      - scripts/replace_sha_hashes.sh
    env:
      TARGET_VARIANT: 'pointer-compression'
    agents:
      image: family/kibana-ubuntu-2004
      provider: gcp
      machineType: n2-standard-2
