env:
  TARGET_VERSION: 18.17.0
  RE2_VERSION: 1.20.1

steps:
  - label: Annotate build with node version
    command:
      - scripts/annotate_build.sh
  
  - label: Build custom node.js artifacts with glibc 2.17 for x64
    command:
      - scripts/create_build_images.sh
      - scripts/build_nodejs.sh
      - scripts/upload_nodejs_artifacts.sh
      # - scripts/build_re2.sh
      # - scripts/upload_re2_artifacts.sh
    env:
      TARGET_ARCH: amd64
    agents:
      image: family/kibana-ubuntu-2004
      imageProject: elastic-images-qa
      provider: gcp
      machineType: c2-standard-16
    timeout_in_minutes: 60 # ideally runs in ~30m

  - label: Build custom node.js artifacts with glibc 2.17 for arm64
    command:
      - scripts/create_build_images.sh
      - scripts/build_nodejs.sh
      - scripts/upload_nodejs_artifacts.sh
      # - scripts/build_re2.sh
      # - scripts/upload_re2_artifacts.sh
    env:
      TARGET_ARCH: arm64
    agents:
      image: family/kibana-ubuntu-2004
      imageProject: elastic-images-qa
      provider: gcp
      localSsds: 8
      localSsdInterface: nvme
      machineType: c2-standard-60
    timeout_in_minutes: 180 # ideally runs in ~2hr

  # - wait

  # - label: Fix SHASUMS256.txt with newly built files' hashes
  #   command:
  #     - scripts/replace_sha_hashes.sh
  #   agents:
  #     image: family/kibana-ubuntu-2004
  #     imageProject: elastic-images-qa
  #     provider: gcp
  #     machineType: n2-standard-2
