steps:
  - command: scripts/build_nodejs.sh
    env:
      ARCH: arm64
    label: Build node.js
    agents:
      image: docker.elastic.co/ci-agent-images/kibana/custom-nodejs-builder:amd64-0.1
    key: build
    timeout_in_minutes: 100
    retry:
      automatic:
        - exit_status: '*'
          limit: 1

  - command: scripts/build_nodejs.sh
    env:
      ARCH: arm64
    label: Build node.js
    agents:
      image: docker.elastic.co/ci-agent-images/kibana/custom-nodejs-builder:arm64-0.1
    key: build
    timeout_in_minutes: 100
    retry:
      automatic:
        - exit_status: '*'
          limit: 1
