steps:
  - label: Upload matrix pipeline
    command:
      - scripts/generate_buildkite_pipeline.sh | buildkite-agent pipeline upload
    agents:
      image: family/kibana-ubuntu-2404
      provider: gcp
      machineType: n2-standard-2
