agents:
  queue: kibana-default

steps:
  - command: scripts/create_build_images.sh

  - wait

  - command:
      - scripts/build_nodejs.sh
    label: Create build images
    env:
      ARCH: amd64
    timeout_in_minutes: 300

  - command: scripts/build_nodejs.sh
    env:
      ARCH: arm64
    label: Build node.js
    timeout_in_minutes: 600
