steps:
  - label: ":buildah: Building Container Images for ARM64"
    branches: "*"
    agents:
      provider: aws
      instanceType: m6g.xlarge
      imagePrefix: drivah-ubuntu-2204-aarch64
    command: |
      uname -m
      buildah --version
      drivah build --changed-since=main ./containers/arm64

  - wait

  - label: ":buildah: Building Container Images for AMD64"
    branches: "*"
    command: |
      buildah --version
      drivah build --changed-since=main ./containers/amd64
