env:
  TARGET_VERSION: 18.16.1
  RE2_VERSION: 1.17.7

steps:
  - label: Annotate build with node version
    command: buildkite-agent annotate "node.js v$${OVERRIDE_TARGET_VERSION:-$$TARGET_VERSION} with glibc 2.17" --style 'info'
    agents:
      queue: kibana-default

  - label: Build custom node.js artifacts with glibc 2.17 for x64
    command:
      - scripts/create_build_images.sh
      - scripts/build_nodejs.sh
      - scripts/upload_nodejs_artifacts.sh
      - scripts/build_re2.sh
      - scripts/upload_re2_artifacts.sh
    env:
      ARCH: amd64
    agents:
      queue: c2-16
    timeout_in_minutes: 60 # ideally runs in ~30m

  - label: Build custom node.js artifacts with glibc 2.17 for arm64
    command:
      - scripts/create_build_images.sh
      - scripts/build_nodejs.sh
      - scripts/upload_nodejs_artifacts.sh
      - scripts/build_re2.sh
      - scripts/upload_re2_artifacts.sh
    env:
      ARCH: arm64
    agents:
      queue: c2-60 # cross-compiling takes a while
    timeout_in_minutes: 180 # ideally runs in ~2hr

  - wait

  - label: Fix SHASUMS256.txt with newly built files' hashes
    command:
      - scripts/replace_sha_hashes.sh
    agents:
      queue: kibana-default
