agents:
  provider: aws
  instanceType: m6g.xlarge
  imagePrefix: drivah-ubuntu-2204-aarch64

steps:
  - label: ":buildah: Building Container Images for ARM64"
    branches: "*"
    command: |
      buildah --version
      drivah build --changed-since=main ./.buildkite/containers/arm64

  # - label: ":buildah: Building Container Images for AMD64"
  #   branches: "*"
  #   command: |
  #     buildah --version
  #     drivah build --changed-since=main ./.buildkite/containers/amd64
