[container.image]
names = ["docker.elastic.co/ci-agent-images/kibana/custom-nodejs-builder"]
tags = ["arm64-0.1"]

[container.image.build_args]
GROUP_ID = 1000
USER_ID = 1000

[docker]
build_flags = [
    "--progress=plain",
    "--platform=linux/arm64",
    "--build-arg=\"GROUP_ID=1000\"",
    "--build-arg=\"USER_ID=1000\""
]
