#!/bin/bash
set -euo pipefail

set -x

uname -a

whoami

pwd

git config --list | cat

git config --global --add url."git@github.com:".insteadOf "https://github.com/"
git config --global --add remote.origin.url."git@github.com:".insteadOf "https://github.com/"

git config --list | cat

set +x
