#!/bin/bash
set -euo pipefail

echo Cleaning up config overrides
git config --list | cat

git config --global --remove url.git@github.com:
git config --global --remove remote.origin.url.git@github.com:

echo After cleanup
git config --list | cat
